services:
  - type: web
    name: suyeoni-flask-db
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: suyeoni-db
          property: connectionString

databases:
  - name: suyeoni-db
    plan: free
