services:
  - type: web
    name: iothub       # 서비스 이름 (원하는 이름으로 바꿔도 됨)
    env: python                     # 파이썬
    plan: free                      # 무료 요금제
    buildCommand: "pip install -r requirements.txt"                # 별도 빌드 명령 없음
    startCommand: "python app.py"   # Flask 앱 실행 명령어
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        value: postgresql://iotdb_33m4_user:foYuwODCSoK8uRWCqy0091PvBoJcahbs@dpg-d44tcmje5dus73fbul4g-a/iotdb_33m4
    rootDir: .
        fromDatabase:
          name: iothub-db
          property: connectionString

databases:
  - name: iothub-db              # 데이터베이스 이름
    plan: free                      # 무료 PostgreSQL
